[package]
name = "advent_of_code"
version = "0.1.0"
authors = ["Xavier Villaneau <xvillaneau@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modinverse = "~0.1"

